apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - cronjob.yaml

images:
  - name: daloman/read-schedule
    newTag: 0.0.13

secretGenerator:
- name: notifications-config
  envs:
  - notifications-config.env